<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_State and City</name>
   <tag></tag>
   <elementGuidId>77df33c7-762b-4bde-88c4-e0d398ac659d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stateCity-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='stateCity-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7cdead8d-84a9-4b21-b226-83dc57e2689f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>6efe1b90-d2e2-43bd-ba39-a257791ef30a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stateCity-label</value>
      <webElementGuid>60c18ee2-7b54-4bf6-b2e3-663cba5866fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>State and City</value>
      <webElementGuid>fe3c74a3-51ba-464c-af9a-1c516fec55c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stateCity-label&quot;)</value>
      <webElementGuid>2df27d78-b6ed-483f-8171-81c5c45da778</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='stateCity-label']</value>
      <webElementGuid>70844adb-1475-4c98-9ea0-e337fc73c26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stateCity-wrapper']/div/label</value>
      <webElementGuid>84e52c7a-98af-440e-ab38-54a74c6a1cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Address'])[1]/following::label[1]</value>
      <webElementGuid>eeee84b0-429a-49b6-a25e-aa038e106adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select picture'])[1]/following::label[2]</value>
      <webElementGuid>15b70b4a-0ac2-4418-805b-00ad1fc67b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rajasthan'])[1]/preceding::label[1]</value>
      <webElementGuid>04de0ce5-a6be-47ba-8f86-36a78619d46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select City'])[1]/preceding::label[1]</value>
      <webElementGuid>1d9df062-cd97-4458-837c-a9142b0abba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='State and City']/parent::*</value>
      <webElementGuid>c678b601-b936-4154-8c57-df335aef1cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/label</value>
      <webElementGuid>2fc59bdb-d299-4adb-984e-38da48ec4b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'stateCity-label' and (text() = 'State and City' or . = 'State and City')]</value>
      <webElementGuid>b6409df1-4828-4ba7-be53-7509d99abf4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
