<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Upload and Download</name>
   <tag></tag>
   <elementGuidId>4fbbf43c-4d30-4b6a-bbeb-1e4ecc108858</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#item-7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='item-7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7eaec000-ef95-40d9-ac64-15b71a0b2426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light </value>
      <webElementGuid>466f24c5-04e0-4396-85b5-5f671b79fdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item-7</value>
      <webElementGuid>162e2bed-61bb-4a2b-9307-d65dbc67768d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload and Download</value>
      <webElementGuid>d753cba6-05d5-49a8-9ad1-70acc5ff8068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;body-height&quot;]/div[@class=&quot;container playgound-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 mt-4  col-md-3&quot;]/div[@class=&quot;left-pannel&quot;]/div[@class=&quot;accordion&quot;]/div[@class=&quot;element-group&quot;]/div[@class=&quot;element-list collapse show&quot;]/ul[@class=&quot;menu-list&quot;]/li[@id=&quot;item-7&quot;]</value>
      <webElementGuid>ff26db8d-b2ff-4430-87b3-e7a446c9f293</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='item-7']</value>
      <webElementGuid>a98d5de4-0fa0-475c-9653-e7cf362eca3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/div/div/div/ul/li[8]</value>
      <webElementGuid>d18c1b4e-eb75-4318-8bb8-32dddae267a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Broken Links - Images'])[1]/following::li[1]</value>
      <webElementGuid>ce975a72-385b-4e57-973e-deb60bfd6f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Links'])[1]/following::li[2]</value>
      <webElementGuid>c23c1de6-765b-4844-a069-2a8a37846100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamic Properties'])[1]/preceding::li[1]</value>
      <webElementGuid>09fc2b72-86c4-44fc-8055-0a42ff3959ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]</value>
      <webElementGuid>ab92c612-5b88-4cba-abd7-715a6e351bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'item-7' and (text() = 'Upload and Download' or . = 'Upload and Download')]</value>
      <webElementGuid>38d2fee1-8d89-4bd4-a6d1-e636bde23c1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
