<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_CfakepathUploadFileExample.txt</name>
   <tag></tag>
   <elementGuidId>8ee57b2c-5acb-4728-966c-462e50851d70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uploadedFilePath</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='uploadedFilePath']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4763f8c8-2cac-4cda-87e0-6d2c5cad9182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadedFilePath</value>
      <webElementGuid>7391fe2f-34a4-4b79-b5ba-08ceb79890fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>C:\fakepath\UploadFileExample.txt</value>
      <webElementGuid>c345d968-341b-497f-b3ec-0d484adea8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadedFilePath&quot;)</value>
      <webElementGuid>ff2e9194-28c6-4cff-99db-37e2f46d6058</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='uploadedFilePath']</value>
      <webElementGuid>3b214790-daa5-4435-8dad-f2787b4bdf53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div[2]/div[2]/p</value>
      <webElementGuid>88dacf17-6588-49f8-b663-ef47aabe0141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a file'])[1]/following::p[1]</value>
      <webElementGuid>c87e2776-45d3-4514-b646-8c32143024fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::p[1]</value>
      <webElementGuid>ff3ebaf7-c4f4-432c-b8ac-861042ef6e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::p[1]</value>
      <webElementGuid>fde96a5e-ae1b-40ec-9b79-c4b64116b85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='C:\fakepath\UploadFileExample.txt']/parent::*</value>
      <webElementGuid>cf901190-d6ca-458b-b035-3f9d68a746f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>285d187a-f5a9-4258-aa0e-c83c767322b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'uploadedFilePath' and (text() = 'C:\fakepath\UploadFileExample.txt' or . = 'C:\fakepath\UploadFileExample.txt')]</value>
      <webElementGuid>7e061cb3-72c7-443c-bf8e-1d7253c783ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
